"""
Aikido curriculum mappings for file-name-decipher lambda.
Scroll names and regex patterns for parsing video file names.
"""

AIKIDO_REGEX_LOOKUP = {
    "bo_drills": r"^a01([0-9]{2})[a-z]$",
    "bo_kata": r"^a02([0-9]{2})[a-z]$",
    "bo_kumite": r"^a03([0-9]{2})[a-z]$",
    "bo_strikes": r"^a04([0-9]{2})[a-z]$",
    "club_and_knife": r"^a05",
    "futaridori": r"^a06([0-9]{2})[a-z]$",
    "gaiden": r"^a07",
    "gokajo": r"^a08",
    "goshin": r"^a09",
    "gun": r"^a10",
    "happo_zanshin": r"^a11",
    "hijiate": r"^a12([0-9]{2})[a-z]$",
    "hijikime": r"^a13([0-9]{2})[a-z]$",
    "hijishime": r"^a14([0-9]{2})[a-z]$",
    "ikkajo": r"^a15([0-9]{2})[a-z]$",
    "iriminage": r"^a16([0-9]{2})[a-z]$",
    "jiyu": r"^a17([0-9]{2})[a-z]$",
    "jo": r"^a18([0-9]{2})[a-z]$",
    "jujinage": r"^a19([0-9]{2})[a-z]$",
    "kaiten_nage": r"^a20([0-9]{2})[a-z]$",
    "katate_mochi": r"^a21([0-9]{2})[a-z]$",
    "kokyunage": r"^a22",
    "koshinage": r"^a23([0-9]{2})[a-z]$",
    "kotegaeshi": r"^a24([0-9]{2})[a-z]$",
    "nikajo": r"^a25([0-9]{2})[a-z]$",
    "push_pull": r"^a26",
    "ryote_mochi": r"^a27([0-9]{2})[a-z]$",
    "sabaki": r"^a28([0-9]{2})[a-z]$",
    "sankajo": r"^a29([0-9]{2})[a-z]$",
    "shihonage": r"^a30([0-9]{2})[a-z]$",
    "shomen_uchi": r"^a31([0-9]{2})[a-z]$",
    "shomen_uchi_advanced": r"^a32([0-9]{2})[a-z]$",
    "sokumen_iriminage": r"^a33([0-9]{2})[a-z]$",
    "tai_otoshi": r"^a34",
    "ten_chi_nage": r"^a35([0-9]{2})[a-z]$",
    "tsuki": r"^a36([0-9]{2})[a-z]$",
    "udegarami": r"^a37([0-9]{2})[a-z]$",
    "ukemi": r"^a38([0-9]{2})[a-z]$",
    "ushironage": r"^a39",
    "yama_arashi": r"^a40",
    "yokomen_uchi_inside": r"^a41([0-9]{2})[a-z]$",
    "yonkajo": r"^a42([0-9]{2})[a-z]$",
    "yubi": r"^a43",
}

AIKIDO_SCROLL_LOOKUP = {
    1: "bo_drills",
    2: "bo_kata",
    3: "bo_kumite",
    4: "bo_strikes",
    5: "club_and_knife",
    6: "futaridori",
    7: "gaiden",
    8: "gokajo",
    9: "goshin",
    10: "gun",
    11: "happo_zanshin",
    12: "hijiate",
    13: "hijikime",
    14: "hijishime",
    15: "ikkajo",
    16: "iriminage",
    17: "jiyu",
    18: "jo",
    19: "jujinage",
    20: "kaiten_nage",
    21: "katate_mochi",
    22: "kokyunage",
    23: "koshinage",
    24: "kotegaeshi",
    25: "nikajo",
    26: "push_pull",
    27: "ryote_mochi",
    28: "sabaki",
    29: "sankajo",
    30: "shihonage",
    31: "shomen_uchi",
    32: "shomen_uchi_advanced",
    33: "sokumen_iriminage",
    34: "tai_otoshi",
    35: "ten_chi_nage",
    36: "tsuki",
    37: "udegarami",
    38: "ukemi",
    39: "ushironage",
    40: "yama_arashi",
    41: "yokomen_uchi_inside",
    42: "yonkajo",
    43: "yubi",
}
